"""Utilities for updating the autogenerated Features section in README.md."""

from __future__ import annotations

import re
from pathlib import Path

START_MARKER = "<!-- AUTO-GENERATED-FEATURES:START -->"
END_MARKER = "<!-- AUTO-GENERATED-FEATURES:END -->"


def build_features_block(features: list[str]) -> str:
    """Create the auto-generated features block content."""
    lines = [START_MARKER, ""]
    for feature in features:
        lines.append(f"- {feature}")
    lines.extend(["", END_MARKER])
    return "\n".join(lines) + "\n"


def update_readme_features(readme_path: str | Path, features: list[str]) -> str:
    """Replace the auto-generated features section in the README while preserving all other content."""
    readme_file = Path(readme_path)
    original = readme_file.read_text(encoding="utf-8")

    block = build_features_block(features)
    start_index = original.find(START_MARKER)
    end_index = original.find(END_MARKER)

    if start_index != -1 and end_index != -1:
        before = original[:start_index]
        after = original[end_index + len(END_MARKER):]
        updated = before + block + after.lstrip("\n")
    elif START_MARKER in original or END_MARKER in original:
        raise ValueError("README contains only one of the required feature markers.")
    else:
        heading = "## Features"
        heading_index = original.find(heading)

        if heading_index != -1:
            after_heading = original[heading_index + len(heading):]
            next_heading_match = re.search(r"\n#+ ", after_heading)

            if next_heading_match is not None:
                next_heading_index = heading_index + len(heading) + next_heading_match.start()
                before = original[:heading_index]
                after = original[next_heading_index:]
                updated = before + heading + "\n\n" + block + "\n" + after.lstrip("\n")
            else:
                before = original[:heading_index]
                after = ""
                updated = before + heading + "\n\n" + block + "\n" + after
        else:
            updated = original.rstrip() + "\n\n" + block

    readme_file.write_text(updated, encoding="utf-8")
    return updated
